name: Check given tag matches semver pattern and is contained in main/master branch


on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      tag:
        required: true
        type: string


    outputs:
      is_publishing_required:
        value: ${{ jobs.check_tag.outputs.is_publishing_required }}


jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - id: check_main_branch
        name: Check whether checked out ref is contained in main or master branch
        run: |
          echo $(git branch --contains);
          
          if git branch --contains | grep -P '(?<!\S)(main|master)(?!\S)'
          then
              echo current ref ${{ inputs.tag }} is contained in main/master branch 
              echo "contained_in_main=y" >> $GITHUB_OUTPUT;
          else
              echo current ref ${{ inputs.tag }} is NOT contained in main/master branch
              echo "contained_in_main=n" >> $GITHUB_OUTPUT
          fi

      - id: check_tag_matches_semver
        name: Check whether supplied tag matches semver regex
        run: |
          echo ${{ inputs.tag }}
          
          if echo ${{ inputs.tag }} | grep -P '(?<!\S)\d+\.\d+\.\d+(?!\S)'
          then
              echo tag ${{ inputs.tag }} matches semver regex
              echo "is_tag_semver=y" >> $GITHUB_OUTPUT
          else
              echo tag ${{ inputs.tag }} does NOT match semver regex
              echo "is_tag_semver=n" >> $GITHUB_OUTPUT
          fi

    outputs:
      is_publishing_required: >-
        ${{ 
          steps.check_main_branch.outputs.contained_in_main == 'y' 
          && 
          steps.check_tag_matches_semver.outputs.is_tag_semver == 'y' 
        }}
