name: Check given tag matches semver pattern and is contained in main/master branch


on:
  workflow_call:
    inputs:
      repository:
        required: true
        type: string
      tag:
        required: true
        type: string


    outputs:
      is_publishing_required:
        value: ${{ jobs.check_tag.outputs.is_publishing_required }}


jobs:
  check_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.tag }}
          fetch-depth: 0

      - name: check_commit_contained_in_main_branch
        run: |
          if [ git branch --contains | grep -P '(?<!\S)(main|master)(?!\S)' ]
          then
              echo contained_in_main_branch=y >> $GITHUB_OUTPUT
          else
              echo contained_in_main_branch=n >> $GITHUB_OUTPUT
          fi

      - name: check_tag_matches_semver
        run: |
          if [ echo ${{ inputs.tag }} | grep -P '(?<!\S)v\d+\.\d+\.\d+(?!\S)' ]
          then
              echo is_tag_semver=y >> $GITHUB_OUTPUT
          else
              echo is_tag_semver=n >> $GITHUB_OUTPUT
          fi
    outputs:
      is_publishing_required: ${{ env.contained_in_main_branch == 'y' && env.is_tag_semver == 'y' }}
