name: Build and publish a Docker image (based on /Dockerfile) into the GitHub Container Registry


on:
  workflow_call:
    inputs:
      image_repository:
        required: true
        type: string
      commit_sha:
        required: true
        type: string


jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build label metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          labels: |
            org.opencontainers.image.description=Docker image ${{ inputs.image_repository}} built from commit SHA ${{ inputs.commit_sha }}.
            org.opencontainers.image.title=Docker image (${{ inputs.image_repository}}:${{ inputs.commit_sha }}).

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ inputs.image_repository }}:${{ inputs.commit_sha }}
          labels: ${{ steps.meta.outputs.labels }}
