name: Build and publish a Docker image (based on /Dockerfile) into the GitHub Container Registry


on:
  workflow_call:
    inputs:
      github_organization:
        required: true
        type: string
      app_name:
        required: true
        type: string
      package_semver_tag:
        required: true
        type: string


jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ inputs.github_organization }}/docker/${{ inputs.app_name }}:${{ inputs.package_semver_tag }}
