name: Build and publish a Docker image (based on /Dockerfile) into the GitHub Container Registry


on:
  workflow_call:
    inputs:
      image_repository:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
  push:
    branches:
      - feature/#116


jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into GHCR
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: true
          tags: ${{ inputs.image_repository }}:${{ inputs.commit_sha }}
