name: Package and publish a Helm chart (located in /helm folder) into the GitHub Container Registry


on:
  workflow_call:
    inputs:
      package_repository:
        required: true
        type: string
      package_semver_tag:
        required: true
        type: string


jobs:
  helm_package_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Install Helm in container
        uses: Azure/setup-helm@v3
        with:
          version: v3.11.1

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Replace placeholders in "values.yaml" and "Chart.yaml"
        run: |
          sed -i \
          -e s~__IMAGE_TAG__~${{ inputs.package_semver_tag }}~ \
          -e s~__IMAGE_REPOSITORY__~${{ inputs.package_repository }}~ \
          helm/values.yaml

      - name: Login to GHCR using Helm
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
          helm registry login -u ${{ github.repository_owner }} --password-stdin ghcr.io

      - name: Package Helm chart and save command output
        run: |
          echo helm_package_output=\
          $(helm package helm --dependency-update \
          --version ${{ inputs.package_semver_tag }} \
          --app-version ${{ inputs.package_semver_tag }}) \
          >> $GITHUB_ENV

      - name: Parse Helm package filename and save it
        run: |
          echo helm_package_file=\
          $(echo ${{ env.helm_package_output }} | grep -P -o '(?<=\s)\S+\.tgz\b') \
          >> $GITHUB_ENV


      - name: Publish Helm chart to GHCR
        run: |
          helm push ${{ env.helm_package_file }} oci://ghcr.io/${{ github.repository_owner }}
