name: "Publishing pipeline: check tag for semver, and if necessary, publish Docker image, publish Helm chart"


on:
  workflow_call:
    inputs:
      github_organization:
        required: true
        type: string
      app_name:
        required: true
        type: string
      git_tag:
        required: true
        type: string
      dockerfile_path:
        type: string
        required: false
        default: ./Dockerfile
      docker_context_path:
        type: string
        required: false
        default: .


jobs:
  check_tag:
    uses: ./.github/workflows/check_tag.yaml
    with:
      git_tag: ${{ inputs.git_tag }}

  publish_docker_image:
    if: fromJSON(needs.check_tag.outputs.is_publishing_required)
    needs:
      - check_tag
    uses: ./.github/workflows/docker_build_publish.yaml
    with:
      github_organization: ${{ inputs.github_organization }}
      app_name:  ${{ inputs.app_name }}
      package_semver_tag: ${{ inputs.git_tag }}
      dockerfile_path:  ${{ inputs.dockerfile_path }}
      docker_context_path: ${{ inputs.docker_context_path }}

  publish_helm_image:
    if: fromJSON(needs.check_tag.outputs.is_publishing_required)
    needs:
      - check_tag
      - publish_docker_image
    uses: ./.github/workflows/helm_package_publish.yaml
    with:
      github_organization: ${{ inputs.github_organization }}
      app_name:  ${{ inputs.app_name }}
      package_semver_tag: ${{ inputs.git_tag }}
