name: "Publishing pipeline: check tag for semver, and if necessary, publish Docker image, publish Helm chart"


on:
  workflow_call:
    inputs:
      github_organization:
        required: true
        type: string
      app_name:
        required: true
        type: string
      git_tag:
        required: true
        type: string


jobs:
  check_tag:
    uses: keeleinstituut/tv-devops/.github/workflows/check_tag.yaml@main # TODO: remove @ref
    with:
      git_tag: ${{ inputs.git_tag }}

  publish_docker_image:
    if: fromJSON(needs.check_tag.outputs.is_publishing_required)
    needs:
      - check_tag
    uses: keeleinstituut/tv-devops/.github/workflows/docker_build_publish.yaml@main # TODO: remove @ref
    with:
      github_organization: ${{ inputs.github_organization }}
      app_name:  ${{ inputs.app_name }}
      package_semver_tag: ${{ inputs.git_tag }}

  publish_helm_image:
    if: fromJSON(needs.check_tag.outputs.is_publishing_required)
    needs:
      - check_tag
      - publish_docker_image
    uses: keeleinstituut/tv-devops/.github/workflows/helm_package_publish.yaml@main # TODO: remove @ref
    with:
      github_organization: ${{ inputs.github_organization }}
      app_name:  ${{ inputs.app_name }}
      package_semver_tag: ${{ inputs.git_tag }}

  debug: # TODO: remove
    if: needs.check_tag.outputs.is_publishing_required
    runs-on: ubuntu-latest
    needs:
      - check_tag
    steps:
      - name: debug
        run: echo ${{ needs.check_tag.outputs.is_publishing_required }}

